spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: qwe123qwe123
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420